language: cpp
os:
    - linux
    - osx

compiler:
    - clang
    - gcc
before_script:
    - cp cmake/* NoahGameFrame && cd NoahGameFrame && chmod +x install.sh && ./install.sh
    - mkdir -p build && cd build && cmake .. && && ls && cat MakeFile

script:
    make -j8
