language: cpp
os:
    - linux
    - osx

compiler:
    - clang
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++4.8" CC="gcc-4.8"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            -clang

before_script:
    - cp -r cmake/* NoahGameFrame && cd NoahGameFrame && chmod +x install.sh && ./install.sh
    - mkdir -p build && cd build && cmake .. && ls && cat Makefile

script:
    make -j8
